# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Kolya/Downloads/design-2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 641, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.create_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.create_Button.setObjectName("create_Button")
        self.gridLayout_2.addWidget(self.create_Button, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.load_back_up_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.load_back_up_Button.setObjectName("load_back_up_Button")
        self.gridLayout_2.addWidget(self.load_back_up_Button, 1, 2, 1, 1)
        self.delete_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delete_Button.setObjectName("delete_Button")
        self.gridLayout_2.addWidget(self.delete_Button, 1, 0, 1, 1)
        self.save_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save_Button.setObjectName("save_Button")
        self.gridLayout_2.addWidget(self.save_Button, 1, 1, 1, 1)
        self.read_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.read_Button.setObjectName("read_Button")
        self.gridLayout_2.addWidget(self.read_Button, 0, 1, 1, 1)
        self.database_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.database_name.setObjectName("database_name")
        self.gridLayout_2.addWidget(self.database_name, 1, 3, 1, 1)
        self.back_up_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.back_up_Button.setObjectName("back_up_Button")
        self.gridLayout_2.addWidget(self.back_up_Button, 0, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 641, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 3, 1, 1)
        self.delete_by_id_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.delete_by_id_Button.setObjectName("delete_by_id_Button")
        self.gridLayout_3.addWidget(self.delete_by_id_Button, 0, 0, 1, 1)
        self.add_Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.add_Button.setObjectName("add_Button")
        self.gridLayout_3.addWidget(self.add_Button, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 4, 1, 1)
        self.id_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.id_1.setObjectName("id_1")
        self.gridLayout_3.addWidget(self.id_1, 1, 1, 1, 1)
        self.phone_num = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.phone_num.setObjectName("phone_num")
        self.gridLayout_3.addWidget(self.phone_num, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.name = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.name.setObjectName("name")
        self.gridLayout_3.addWidget(self.name, 1, 2, 1, 1)
        self.surname = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.surname.setObjectName("surname")
        self.gridLayout_3.addWidget(self.surname, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 180, 641, 86))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_5.addWidget(self.pushButton_12, 1, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 5, 1, 1)
        self.new_name = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.new_name.setObjectName("new_name")
        self.gridLayout_5.addWidget(self.new_name, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 4, 1, 1)
        self.id_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.id_2.setObjectName("id_2")
        self.gridLayout_5.addWidget(self.id_2, 1, 1, 1, 1)
        self.new_id = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.new_id.setObjectName("new_id")
        self.gridLayout_5.addWidget(self.new_id, 1, 2, 1, 1)
        self.new_phone_num = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.new_phone_num.setObjectName("new_phone_num")
        self.gridLayout_5.addWidget(self.new_phone_num, 1, 5, 1, 1)
        self.new_surname = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.new_surname.setObjectName("new_surname")
        self.gridLayout_5.addWidget(self.new_surname, 1, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 270, 641, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.print_data = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.print_data.setObjectName("print_data")
        self.verticalLayout_3.addWidget(self.print_data)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_Button.setText(_translate("MainWindow", "Create"))
        self.label_3.setText(_translate("MainWindow", "DateBase Name:"))
        self.load_back_up_Button.setText(_translate("MainWindow", "load back_up"))
        self.delete_Button.setText(_translate("MainWindow", "Delete"))
        self.save_Button.setText(_translate("MainWindow", "Save"))
        self.read_Button.setText(_translate("MainWindow", "Read"))
        self.back_up_Button.setText(_translate("MainWindow", "back_up"))
        self.label_6.setText(_translate("MainWindow", "Surname"))
        self.delete_by_id_Button.setText(_translate("MainWindow", "Delete by ID"))
        self.add_Button.setText(_translate("MainWindow", "Add"))
        self.label_7.setText(_translate("MainWindow", "Phone number"))
        self.label_4.setText(_translate("MainWindow", "ID"))
        self.label_5.setText(_translate("MainWindow", "Name"))
        self.pushButton_12.setText(_translate("MainWindow", "Edit"))
        self.pushButton_11.setText(_translate("MainWindow", "Find by ID"))
        self.label_14.setText(_translate("MainWindow", "new Name"))
        self.label_16.setText(_translate("MainWindow", "new Phone number"))
        self.label_13.setText(_translate("MainWindow", "new ID"))
        self.label_15.setText(_translate("MainWindow", "new Surname"))
        self.label_12.setText(_translate("MainWindow", "ID"))
        self.print_data.setText(_translate("MainWindow", "Print Data"))
